baseURL = "http://securelayer.co"
languageCode = "en-us"
title = "SecureLayer"
theme = "agnes-hugo-theme"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "SecureLayer"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "/contact"
		#pageRef = '/contact'
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "/about"
		#pageRef = '/about'
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "/faq"
		#pageRef = '/faq'	
		weight = 3
		
[params.social]
	GoogleURL = "http://google.com"
		
[params.content]
	LeadTitle = "SecureLayer"
	LeadDescription = "a cybersecurity company helping SMBs improve their business in Europe, South America and the Caribbean."
	ButtonCaption = "Contact Us"
	ButtonURL = "/contact"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Virtual CISO"
	FeatureDescription = "to have a cybersecurity expert at your disposal for a comprehensive and tailored cyber security strategy to help you meet your business goals."
 	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Managed Security"
	FeatureDescription = "to implement cybersecurity tools at an affordable price and give your organization access to the best technologies to protect your business."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Risk Assessment"
	FeatureDescription = "to identify real vulnerabilities in your systems and take effective actions."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Phishing Test"
	FeatureDescription = "to train your employees and minimize the effects of any attacks that will break through."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Pro"
	PricingRate = "250"	
	ButtonCaption = "Contact Us"
 	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "*1 Risk Assessment* of your system"
	[[params.pricing.Features]]
		Description = "*1 Hour* of our *vCISO* Services"
	[[params.pricing.Features]]
		Description = "*1 Device* covered by our basic *Managed Security* Services (+50$ by added device)"	

[[params.pricing]]
	PricingTitle = "Business+"
	PricingRate = "750"
	ButtonCaption = "Contact Us"
 	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "*1 Risk Assessment* of your system"
	[[params.pricing.Features]]
		Description = "*4 Hours* of our *vCISO* Services"
	[[params.pricing.Features]]
		Description = "*2 Device* covered by our basic *Managed Security* Services (+50$ by added device)"
	[[params.pricing.Features]]
		Description = "Basic *Website and Network Security* Management"

[[params.pricing]]
	PricingTitle = "Entreprise"
	PricingRate = "-"
	ButtonCaption = "Get Earliest Access"
 	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "Regular *Risk Assessment* of your system"
	[[params.pricing.Features]]
		Description = "Full *vCISO* Services"
	[[params.pricing.Features]]
		Description = "All devices covered by our advanced *Managed Security* Services"
	[[params.pricing.Features]]
		Description = "Advanced *Website and Network Security* Management" 
