baseURL = "http://securelayer.co/"
languageCode = "en-us"
title = "SecureLayer"
theme = "agnes-hugo-theme"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "SecureLayer"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		#URL = "#"
		pageRef = '/contact'
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		#URL = "#"
		pageRef = '/about'
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		#URL = "#"
		pageRef = '/faq'	
		weight = 3
		
[params.social]
	GoogleURL = "http://google.com"
		
[params.content]
	LeadTitle = "SecureLayer"
	LeadDescription = "a cybersecurity company providing services for SMBs in Europe, South America and the Caribbean."
	ButtonCaption = "Contact Us"
	ButtonURL = "/contact"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Virtual CISO"
	FeatureDescription = "a cybersecurity expert will take the time to understand your organization’s specific business objectives and create a comprehensive and tailored cyber security strategy to meet those goals."
 	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Managed Security"
	FeatureDescription = "cybersecurity tools at an affordable price to give your organization access to best technologies that fit your requirements and budget."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Risk Assessment"
	FeatureDescription = "to inform decision-makers about vulnerabilities in corporate systems, allowing them to take preemptive defensive actions and prepare effective risk responses."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Phishing Test"
	FeatureDescription = "to train your employees to detect and report phishing attacks to minimize the effects of attacks that will break through."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Pro"
	PricingRate = "250"	
	ButtonCaption = "Contact Us"
	[[params.pricing.Features]]
		Description = "1 Hour Of Advisory Services"
	[[params.pricing.Features]]
		Description = "1 Hour of Incident Response Services"
	[[params.pricing.Features]]
		Description = "1 Device Security Management (+50$ by added device)"	

[[params.pricing]]
	PricingTitle = "Business+"
	PricingRate = "750"
	ButtonCaption = "Contact Us"
	[[params.pricing.Features]]
		Description = "4 Hours Of Advisory Services"
	[[params.pricing.Features]]
		Description = "4 Hours of Incident Response Services"
	[[params.pricing.Features]]
		Description = "2 Devices Security Management (+50$ by added device)"
	[[params.pricing.Features]]
		Description = "Network Security Management"
	
[[params.pricing]]
	PricingTitle = "Entreprise"
	PricingRate = "-"
	ButtonCaption = "Get Earliest Access"
	[[params.pricing.Features]]
		Description = "Full Advisory & Incident Response Services"
	[[params.pricing.Features]]
		Description = "Full Devices Security Management"
	[[params.pricing.Features]]
		Description = "Security Strategy Roadmap"
	[[params.pricing.Features]]
		Description = "Secure Project Implementation"
  	[[params.pricing.Features]]
		Description = "Network Security Management"
