baseURL = "http://securelayer.co/"
languageCode = "en-us"
title = "SecureLayer"
theme = "agnes-hugo-theme"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "SecureLayer"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "#"
		weight = 3
	
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 4
		
[params.social]
	GoogleURL = "http://google.com"
		
[params.content]
	LeadTitle = "SecureLayer"
	LeadDescription = "a cybersecurity company providing services for SMBs in Europe, South America and the Caribbean."
	ButtonCaption = "Pricing & Plans"
	ButtonURL = "http://google.com"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Virtual CISO"
	FeatureDescription = "From zero to secure in weeks – Plan, develop, and implement an effective cyber security strategy"
 	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Managed Security"
	FeatureDescription = "Enterprise solutions at an affordable price - Our managed security services give your organization access to best-in-class experts, proven processes, and cutting-edge technologies that fit your requirements and budget."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Risk Assessment"
	FeatureDescription = " Identify, evaluate, and prioritize cyber risk - We believe that true risk assessment lies with the organization as a whole, rather than individual technologies. With us, you will understand all of your risks."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Phishing Test"
	FeatureDescription = "To train employees to detect and report phishing - We believe in an approaach to arms employees with knowledge and best practices to will attacks from succeeding or minimize the effects of those that break through."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Pro"
	PricingRate = "250"	
	ButtonCaption = "Contact Us"
	[[params.pricing.Features]]
		Description = "1 Hour Of Advisory Services"
	[[params.pricing.Features]]
		Description = "1 Hour of Incident Response Services"
	[[params.pricing.Features]]
		Description = "1 Device Security Management (+50$ by added device)"	

[[params.pricing]]
	PricingTitle = "Business+"
	PricingRate = "750"
	ButtonCaption = "Contact Us"
	[[params.pricing.Features]]
		Description = "4 Hours Of Advisory Services"
	[[params.pricing.Features]]
		Description = "4 Hours of Incident Response Services"
	[[params.pricing.Features]]
		Description = "2 Devices Security Management (+50$ by added device)"
	[[params.pricing.Features]]
		Description = "Network Security Management"
	
[[params.pricing]]
	PricingTitle = "Entreprise"
	PricingRate = "on Demand"
	ButtonCaption = "Get Earliest Access"
	[[params.pricing.Features]]
		Description = "Full Advisory & Incident Response Services"
	[[params.pricing.Features]]
		Description = "Full Devices Security Management"
	[[params.pricing.Features]]
		Description = "Security Strategy Roadmap"
	[[params.pricing.Features]]
		Description = "Secure Project Implementation"
  	[[params.pricing.Features]]
		Description = "Network Security Management"
