baseURL = "http://securelayer.co"
languageCode = "en-us"
title = "SecureLayer"
theme = "agnes-hugo-theme"
contentDir = "content/en"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "SecureLayer"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "mailto:contact@securelayer.co"
		#pageRef = '/contact'
		weight = 1
	
	[[menu.main]]
		Name = "Security"
		URL = "/security"
		weight = 2
	
	[[menu.main]]
		Name = "Privacy"
		URL = "/privacy"
		weight = 3
		
#[params.social]
	#GoogleURL = "http://google.com"
		
[params.content]
	LeadTitle = "SecureLayer"
	LeadDescription = "We help SMBs improve organization's ability to prevent, withstand and recover from cybersecurity incidents."
	ButtonCaption = "Send us an email"
	ButtonURL = "mailto:contact@securelayer.co"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Virtual CISO"
	FeatureDescription = "Have a cybersecurity expert at your disposal for a comprehensive and tailored cyber security strategy to help you meet your business goals."
 	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Managed Security"
	FeatureDescription = "Implement cybersecurity tools at an affordable price and give your organization access to the best technologies and protect your business."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Risk Assessment"
	FeatureDescription = "Identify real vulnerabilities in your systems and take effective actions."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Website and Network Security"
	FeatureDescription = "Protect the data of your customers and minimize the effects of any attacks that will break through."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Pro"
	PricingRate = ""	
	ButtonCaption = "Contact us"
	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "1 Risk Assessment of your system"
	[[params.pricing.Features]]
		Description = "1 Hour of our Virtual CISO Services"
	[[params.pricing.Features]]
		Description = "1 Device covered by our basic Managed Security Services"	

[[params.pricing]]
	PricingTitle = "Business+"
	PricingRate = ""
	ButtonCaption = "Contact us"
	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "1 Risk Assessment of your system"
	[[params.pricing.Features]]
		Description = "4 Hours of our Virtual CISO Services"
	[[params.pricing.Features]]
		Description = "2 Devices covered by our basic Managed Security Services"
	[[params.pricing.Features]]
		Description = "Basic Website and Network Security Management"

[[params.pricing]]
	PricingTitle = "Entreprise"
	PricingRate = ""
	ButtonCaption = "Get Earliest Access"
	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "Regular Risk Assessment of your system"
	[[params.pricing.Features]]
		Description = "Full Virtual CISO Services"
	[[params.pricing.Features]]
		Description = "All devices covered by our advanced Managed Security Services"
	[[params.pricing.Features]]
		Description = "Advanced Website and Network Security Management" 
