baseURL = "http://securelayer.co"
languageCode = "en-us"
title = "SecureLayer"
theme = "agnes-hugo-theme"
contentDir = "content/en"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "SecureLayer"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "mailto:contact@securelayer.co"
		#pageRef = '/contact'
		weight = 1
	
	[[menu.main]]
		Name = "Security"
		URL = "/security"
		weight = 2
	
	[[menu.main]]
		Name = "Privacy"
		URL = "/privacy"
		weight = 3
		
#[params.social]
	#GoogleURL = "http://google.com"
		
[params.content]
	LeadTitle = "SecureLayer"
	LeadDescription = "We help small and medium-sized enterprises (SMEs) improve their ability to prevent, withstand and recover from cybersecurity incidents."
	ButtonCaption = "Improve Your Cybersecurity Now" 
	ButtonURL = "mailto:contact@securelayer.co"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Virtual CISO"
	FeatureDescription = "Reach a cybersecurity expert to answer your questions or to help you maintain your business operations after an incident."
 	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Managed Security"
	FeatureDescription = "Implement cybersecurity tools (DDos & Malware protections, VPN, Password Manager...) at an affordable price to protect your business."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Risk Assessment"
	FeatureDescription = "Identify vulnerabilities in your systems and take effective corrective actions."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Corporate, Website and Network Security"
	FeatureDescription = "Protect the data of your customers and minimize the effects any cyberattacks that will break through."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "vCISO à la demande"
	PricingRate = ""	
	ButtonCaption = "Get Instant Quote"
	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "Incident Reponse"
	[[params.pricing.Features]]
		Description = "CyberSecurity Guidance"
	[[params.pricing.Features]]
		Description = "CyberSecurity Assessment"	

[[params.pricing]]
	PricingTitle = "vCISO project"
	PricingRate = ""
	ButtonCaption = "Get Instant Quote"
	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "3-6-9-12 months projects"
	[[params.pricing.Features]]
		Description = "Secured API, Secured GenAI, Zero Trust, Security awareness program"
	[[params.pricing.Features]]
		Description = "Compliance, Cybersecurity strategy, Risk management"
	[[params.pricing.Features]]
		Description = "Website, Corporate, Network Cybersecurity Projects"

[[params.pricing]]
	PricingTitle = "vCISO part-time"
	PricingRate = ""
	ButtonCaption = "Get Instant Quote"
	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "Detect and mitigate cyberattacks"
	[[params.pricing.Features]]
		Description = "Website, Corporate or Network Security Management"
	[[params.pricing.Features]]
		Description = "Incident Reponses & Vendors Management"
	[[params.pricing.Features]]
		Description = "CyberSecurity training" 
