baseURL = "http://securelayer.co"
languageCode = "en-us"
title = "SecureLayer"
theme = "agnes-hugo-theme"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "SecureLayer"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "/contact"
		#pageRef = '/contact'
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "/about"
		#pageRef = '/about'
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "/faq"
		#pageRef = '/faq'	
		weight = 3
		
[params.social]
	GoogleURL = "http://google.com"
		
[params.content]
	LeadTitle = "SecureLayer"
	LeadDescription = "a cybersecurity company helping SMBs improve their business in Europe, South America and the Caribbean."
	ButtonCaption = "Contact Us"
	ButtonURL = "/contact"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Virtual CISO"
	FeatureDescription = "a cybersecurity expert at your disposal to create a comprehensive and tailored cyber security strategy in order to meet your business goals."
 	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Managed Security"
	FeatureDescription = "to implement cybersecurity tools at an affordable price and give your organization access to the best technologies to protect your business."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Risk Assessment"
	FeatureDescription = "to identify real vulnerabilities in your systems and take effective actions."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Phishing Test"
	FeatureDescription = "to train your employees and minimize the effects of any attacks that will break through."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Pro"
	PricingRate = "250"	
	ButtonCaption = "Contact Us"
 	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "1 Hour Of Advisory Services"
	[[params.pricing.Features]]
		Description = "1 Hour of Incident Response Services"
	[[params.pricing.Features]]
		Description = "1 Device Security Management (+50$ by added device)"	

[[params.pricing]]
	PricingTitle = "Business+"
	PricingRate = "750"
	ButtonCaption = "Contact Us"
 	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "4 Hours Of Advisory Services"
	[[params.pricing.Features]]
		Description = "4 Hours of Incident Response Services"
	[[params.pricing.Features]]
		Description = "2 Devices Security Management (+50$ by added device)"
	[[params.pricing.Features]]
		Description = "Network Security Management"
	
[[params.pricing]]
	PricingTitle = "Entreprise"
	PricingRate = "-"
	ButtonCaption = "Get Earliest Access"
 	pageRef = '/contact'
	[[params.pricing.Features]]
		Description = "Full Advisory & Incident Response Services"
	[[params.pricing.Features]]
		Description = "Full Devices Security Management"
	[[params.pricing.Features]]
		Description = "Security Strategy Roadmap"
	[[params.pricing.Features]]
		Description = "Secure Project Implementation"
  	[[params.pricing.Features]]
		Description = "Network Security Management"
